In [2]:
import boto3
import sagemaker
from sagemaker import get_execution_role
import sys
import IPython

In [4]:
if int(sagemaker.__version__.split('.')[0]) == 2:
    print("Installing previous Sagemaker version and restarting the kernel")
    !{sys.executable} -m pip install sagemaker==1.72.0
    IPython.Application.instance().kernel.do_shutdown(True)

else:
    print("version is good!")

version is good!

In [5]:
sagemaker.__version__

'1.72.0'

In [6]:
role = get_execution_role()
sess = sagemaker.Session()
region = boto3.session.Session().region_name
sm = boto3.Session().client('sagemaker')

In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from time import sleep, gmtime, strftime
import json
import time

In [8]:
!pip install sagemaker-experiments
from sagemaker.analytics import ExperimentAnalytics
from smexperiments.experiment import Experiment
from smexperiments.trial import Trial
from smexperiments.trial_component import TrialComponent
from smexperiments.tracker import Tracker

/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: sagemaker-experiments in /opt/conda/lib/python3.7/site-packages (0.1.35)
Requirement already satisfied: boto3>=1.16.27 in /opt/conda/lib/python3.7/site-packages (from sagemaker-experiments) (1.20.4)
Requirement already satisfied: botocore<1.24.0,>=1.23.4 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.16.27->sagemaker-experiments) (1.23.4)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.16.27->sagemaker-experiments) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.16.27->sagemaker-experiments) (0.5.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.7/site-packages (from botocore<1.24.0,>=1.23.4->boto3>=1.16.27->sagemaker-experiments) (1.26.7)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.7/site-packages (from botocore<1.24.0,>=1.23.4->boto3>=1.16.27->sagemaker-experiments) (2.8.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.24.0,>=1.23.4->boto3>=1.16.27->sagemaker-experiments) (1.14.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [9]:
    rawbucket = sess.default_bucket() # default session bucket; sagemaker EBS volume
    
    prefix = "sagemaker-modelmonitor" # using this prefix to store all files in this workshop
    
    dataprefix = prefix + "/data"
    traindata_prefix = prefix + "/train_data"
    testdata_prefix = prefix + "/test_data"
    testdata_nolabel_prefix = prefix + "/test_data_no_label"
    trainheader_prefix = prefix + "/train_headers"

In [10]:
## downloading the dataset and importing it using pandas 
! wget https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls

--2021-11-27 15:39:40--  https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5539328 (5.3M) [application/x-httpd-php]
Saving to: ‘default of credit card clients.xls.2’

default of credit c 100%[===================>]   5.28M  8.47MB/s    in 0.6s

2021-11-27 15:39:42 (8.47 MB/s) - ‘default of credit card clients.xls.2’ saved [5539328/5539328]

In [11]:
data = pd.read_excel('default of credit card clients.xls', header=1)
data = data.drop(columns=["ID"])
data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

as amazon sagemaker's inhouse xgb algorithm requires the label to be the first column, so we are making the necessary arrangements

In [12]:
data.rename(columns={"default payment next month": "Label"}, inplace=True)
lbl = data.Label
data = pd.concat([lbl, data.drop(columns=['Label'])], axis=1)
data.head()

,Label,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000,2,2,1,24,2,2,-1,-1,...,689,0,0,0,0,689,0,0,0,0
1,1,120000,2,2,2,26,-1,2,0,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,0,90000,2,2,2,34,0,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,0,50000,2,2,1,37,0,0,0,0,...,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,0,50000,1,2,1,57,-1,0,-1,0,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679

uploading the csv dataset in a s3 bucket

In [13]:
if not os.path.exists('rawdata/rawdata.csv'):
    !mkdir rawdata
    data.to_csv('rawdata/rawdata.csv', index=None)
else:
    pass

# upload dataset
raw_data_location = sess.upload_data('rawdata', bucket=rawbucket, key_prefix=dataprefix)
print(raw_data_location)

s3://sagemaker-us-east-1-908912589397/sagemaker-modelmonitor/data

above url represents link to s3 bucket for this data

PROCESSING DATA USING SAGEMAKER PROCESSING

In [14]:
from sagemaker.sklearn.processing import SKLearnProcessor

sklearn_processor = SKLearnProcessor(framework_version='0.20.0',
                                    role=role,
                                    instance_type='ml.c4.xlarge',
                                    instance_count=1)

In [15]:
%%writefile preprocessing.py


import argparse
import os
import warnings

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.exceptions import DataConversionWarning
from sklearn.compose import make_column_transformer

warnings.filterwarnings(action='ignore', category=DataConversionWaring)

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--train-test-split-ratio', type=float, default=0.3)
    parser.add_argument('--random-split', type=int, default=0)
    args, _ = parser.parse_known_args()
    
    
    print('Received arguments {}'.format(args))
    
    
    input_data_path = os.path.join('/opt/ml/processing/input', 'rawdata.csv')
    
    print(f'Reading input data from {input_data_path})')
    df = pd.read_csv(input_data_path)
    df.sample(frac=1)
    
    
    COLS = df.columns
    newcolororder = ['PAY_AMT1', 'BILL_AMT1'] + list(COLS[1:])[:11] + list(COLS[1:][12:17]) + list(COLS[1:])[18:]
    
    split_ratio = args.train_test_split_ratio
    random_state = args.random_split
    
    
    X_train, X_test, y_train, y_test = train_test_split(df.drop('Label', axis=1), df['Label'],
                                                       test_size=split_ratio, random_state=random_state)
    
    preprocess = make_column_transformer(
                    (['PAY_AMT1'], StandardScaler()),
                    (['BILL_AMT1'], MinMaxScaler()),
                    remainder='passthrough')
    
    print('Running preprocessing and feature engineering transformations')
    train_features = pd.DataFrame(preprocess.fit_transform(X_train), columns = newcolorder)
    test_features = pd.DataFrame(preprocess.transform(X_test), columns = newcolorder)
    
    # concat to ensure 'Label' is the first columns in dataframe
    train_full = pd.concat([pd.DataFrame(y_train.values, columns=['Label']), train_features], axis=1)
    test_full = pd.concat([pd.DataFrame(y_test.values, columns=['Label']), test_features], axis=1)
    
    
    print('Train data shape after preprocessing: {}'.format(train_features.shape))
    print('Test data shape after preprocessing: {}'.format(test_features.shape))
    
    
    train_features_headers_output_path = os.path.join('/opt/ml/processing/train_headers', 'train_data_with_headers.csv')
    train_features_output_path = os.path.join('/opt/ml/processing/train', 'train_data.csv')
    test_features_output_path = os.path.join('/opt/ml/processing/test', 'test_data.csv')
    
    print('Saving training features to {}'.format(train_features_output_path))
    train_full.to_csv(train_features_output_path, header=False, index=False)
    print('Complete!')
    
    print('Save training data with headers to {}'.format(train_features_headers_output_path))
    train_full.to_csv(train_features_headers_output_path, index=False)
    
    print('Saving test features to {}'.format(test_features_output_path))
    test_full.to_csv(test_features_output_path, header=False, index=False)
    print('Complete!')

Writing preprocessing.py

In [16]:
# copy the processing code over to s3 bucket
codeprefix = prefix + '/code'
codeupload = sess.upload_data('preprocessing.py', bucket=rawbucket, key_prefix=codeprefix)
print(codeupload)

s3://sagemaker-us-east-1-908912589397/sagemaker-modelmonitor/code/preprocessing.py

In [18]:
# store training and test data after processing job is over
train_data_location = rawbucket + '/' + traindata_prefix
test_data_location = rawbucket + '/' + testdata_prefix
print('Training data location: {}'.format(train_data_location))
print('Test data location: {}'.format(test_data_location))

Training data location: sagemaker-us-east-1-908912589397/sagemaker-modelmonitor/train_data
Test data location: sagemaker-us-east-1-908912589397/sagemaker-modelmonitor/test_data

In [ ]:
from sagemaker.processing import ProcessingInput, ProcessingOutput


sklearn_processor.run(code=codeupload,
                     inputs=[ProcessingInput(source=raw_data_location, desination='/opt/ml/processing/input')],
                     outputs=[ProcessingOutput(output_name='train_data', source='/opt/ml/processing/train',
                             destination='s3://' + train_data_location),
                             ])